# Generated by Django 5.1.7 on 2025-04-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('sclass', models.IntegerField()),
                ('saddress', models.CharField(max_length=100)),
            ],
        ),
    ]
